### ISSUE TITLE
Documentation: Add example + clarify how to use `result` stdout/stderr output when using API

### ISSUE THREAD

**Issue by pirate** [Fizzadar/pyinfra#1213]
This part of the docs explains how to use result stdout/stderr:  
https://docs.pyinfra.com/en/3.x/using-operations.html#operation-output

But it's not clear how to do this via the API. This doesn't appear to work:

```python
from pyinfra import operations
from pyinfra.api import Config, Inventory, State
from pyinfra.api.connect import connect_all
from pyinfra.api.operation import add_op
from pyinfra.api.operations import run_ops
from pyinfra.api.exceptions import PyinfraError

config = Config()
inventory = Inventory((["@local"], {}))
state = State(inventory=inventory, config=config)

connect_all(state)

# try to do some operation first, storing result
result = add_op(
    state,
    operations.server.packages,
    packages='ffmpeg',
)

# create a global to hold the result stdout/stderr
ERROR_MSG = None

# add an op to store the stderr/stdout in the global variable
def callback():
    ERROR_MSG = result.stderr + '\n' + result.stdout

add_op(
    state,
    operations.python.call,
    function=callback,
)

print("INSTALLING PACKAGE: ffmpeg")
try:
    run_ops(state)
    print("SUCCESS")
except PyinfraError:
    # does not work
    print("FAILED", ERROR_MSG)
```

Throws this error, indicating `add_op` doesn't return a `result` object in the same way that calling an op directly does:
```python3
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "~/Desktop/pyinfra-test/.venv/lib/python3.11/site-packages/pyinfra/api/command.py", line 231, in execute_function
    self.function(*self.args, **self.kwargs)
  File "~/Desktop/pyinfra-test/main.py", line 45, in callback
    ERROR_MSG = result.stderr + '\n' + result.stdout
                   ^^^^^^
AttributeError: 'dict' object has no attribute 'stderr'
2024-09-21T00:57:51Z <Greenlet at 0x1066fd440: execute_function> failed with AttributeError
```

Trying to access the result stderr through `state.op_meta` also doesn't work:
```python
ipdb> state.op_meta['784a97bf1955d5f7a2b9dd6c1e371e17b73c42bc'].stderr
*** AttributeError: 'StateOperationMeta' object has no attribute 'stderr'
```

**Comment by pirate** [comment]
Figured it out, `result` is actually a dictory [`Dict[Host, OperationMeta]`](https://github.com/pyinfra-dev/pyinfra/blob/3.x/pyinfra/api/operation.py#L43), so it's pretty easy:

```python
...

result = add_op(...)

run_ops(state)

# get operation result for localhost
op_result: OperationMeta = result[state.inventory.hosts['@local']]

print(op_result.changed, op_result.stdout, op_result.stderr)
```

Fixed by adding this to my docs example PR here: [`ff0fa1f` (#1212)](https://github.com/pyinfra-dev/pyinfra/pull/1212/commits/ff0fa1ffe2d55ba291456cd9f54a9cc31d97d1e2)
