### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by tobald** [Fizzadar/pyinfra#143]
There is one test failing when trying to build pyinfra with pybuild/sbuild (PYBUILD_TEST_ARGS="python3 -m nose --verbose"):

```
======================================================================
FAIL: test_bad_deploy_file (tests.test_cli.TestCliExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_cli.py", line 133, in test_bad_deploy_file
    'No deploy file: nop.py',
  File "/<<PKGBUILDDIR>>/tests/test_cli.py", line 127, in assert_cli_exception
    self.assertIsInstance(self.exception, CliError)
AssertionError: None is not an instance of <class 'pyinfra_cli.exceptions.CliError'>

======================================================================
FAIL: test_bad_fact (tests.test_cli.TestCliExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_cli.py", line 139, in test_bad_fact
    'No fact: thing',
  File "/<<PKGBUILDDIR>>/tests/test_cli.py", line 127, in assert_cli_exception
    self.assertIsInstance(self.exception, CliError)
AssertionError: None is not an instance of <class 'pyinfra_cli.exceptions.CliError'>
```

unittest says:

```
 DeprecationWarning: 'message' is an invalid keyword argument for this function
  with self.assertRaises(CliError, message='Deploy file not found: nop.py'):
/home/chris/repositories/debian/pyinfra/.pybuild/pythonX.Y_3.5/build/tests/test_cli.py:184: DeprecationWarning: 'message' is an invalid keyword argument for this function
  CliError, message='Private key file not found: nop.key',
[…]
======================================================================
FAIL: test_bad_deploy_file (tests.test_cli.TestCliExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/repositories/debian/pyinfra/.pybuild/pythonX.Y_3.5/build/tests/test_cli.py", line 133, in test_bad_deploy_file
    'No deploy file: nop.py',
  File "/home/chris/repositories/debian/pyinfra/.pybuild/pythonX.Y_3.5/build/tests/test_cli.py", line 128, in assert_cli_exception
    self.assertEqual(self.exception.message, message)
AssertionError: 'No deploy file: example/deploy.py' != 'No deploy file: nop.py'
- No deploy file: example/deploy.py
+ No deploy file: nop.py
```

**Comment by Fizzadar** [comment]
@tobald is this still happening with the latest changes? I think I fixed certainly the `test_bad_deploy_file` one...

**Comment by tobald** [comment]
Still failing here:

```
~/repositories/pyinfra/.pybuild/pythonX.Y_3.5/build$ python3.5 -m unittest discover -v
======================================================================
FAIL: test_bad_deploy_file (tests.test_cli.TestCliExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/repositories/pyinfra/.pybuild/pythonX.Y_3.5/build/tests/test_cli.py", line 120, in test_bad_deploy_file
    'No deploy file: nop.py',
  File "/home/chris/repositories/pyinfra/.pybuild/pythonX.Y_3.5/build/tests/test_cli.py", line 115, in assert_cli_exception
    self.assertEqual(self.exception.message, message)
AssertionError: 'No deploy file: example/deploy.py' != 'No deploy file: nop.py'
- No deploy file: example/deploy.py
+ No deploy file: nop.py


----------------------------------------------------------------------
Ran 257 tests in 0.184s

```

**Comment by Fizzadar** [comment]
I _think_ I've fixed this @ https://github.com/Fizzadar/pyinfra/commit/38a9ef4f945c0bb44438fe3f017db36345c9bc3b :)

**Comment by tobald** [comment]
yes, thank you.
