### ISSUE TITLE
Why must the `--key` be specified when running a deploy from another directory?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#244]
I was working on an example interacting with digital ocean. I spun up a digital ocean instance. Then I wanted to run a deploy from a parent directory and it threw an exception. If I pass the `--key` there is no exception.

This feels like a bug to me.

Steps I went thru:
1. Used more-examples branch on commit https://github.com/mkinney/pyinfra/commit/8c49809ea5bc31e724547c3500f54fe5a17575c3 
2. Created a vm in examples/digitalocean directory:`./do.py add`
3. Ensure I can access vm: `pyinfra --user root 64.225.38.33 exec -- sudo echo hello`
4. Ran: `pyinfra --user root 64.225.38.33 ../docker_ce.py`
5. If I add the `--key ~/.ssh/id_rsa` to command in prior step, there is no error.

```
$ pyinfra --user root 64.225.38.33 ../docker_ce.py
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/host.py", line 82, in connect
    self.connection = self.executor.connect(state, self, *args, **kwargs)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 149, in connect
    kwargs = _make_paramiko_kwargs(state, host)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 132, in _make_paramiko_kwargs
    key_password=host.data.ssh_key_password,
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 103, in _get_private_key
    raise IOError('No such private key file: {0}'.format(key_filename))
OSError: No such private key file: files/insecure_private_key
2020-01-19T17:35:37Z <Greenlet at 0x10b797dd0: <bound method Host.connect of 64.225.38.33>(<pyinfra.api.state.State object at 0x10b8e1f50>)> failed with OSError

--> An unexpected exception occurred:

  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 103, in _get_private_key
    raise IOError('No such private key file: {0}'.format(key_filename))
OSError: No such private key file: files/insecure_private_key

--> The full traceback has been written to pyinfra-debug.log
```

```
$ cat pyinfra-debug.log
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra_cli/main.py", line 195, in main
    _main(*args, **kwargs)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra_cli/main.py", line 434, in _main
    connect_all(state)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connect.py", line 35, in connect_all
    greenlet.get()
  File "src/gevent/greenlet.py", line 683, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/host.py", line 82, in connect
    self.connection = self.executor.connect(state, self, *args, **kwargs)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 149, in connect
    kwargs = _make_paramiko_kwargs(state, host)
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 132, in _make_paramiko_kwargs
    key_password=host.data.ssh_key_password,
  File "/Users/mikekinney/Documents/python/mkinney_pyinfra/pyinfra/api/connectors/ssh.py", line 103, in _get_private_key
    raise IOError('No such private key file: {0}'.format(key_filename))
OSError: No such private key file: files/insecure_private_key
```

**Comment by Fizzadar** [comment]
ARgh my bad, this is my fault - https://github.com/Fizzadar/pyinfra/blob/master/examples/group_data/all.py#L7 - removed @ https://github.com/Fizzadar/pyinfra/commit/ce574c5c2f014d5189bccc130c934312f6f4e6e3.

**Comment by mkinney** [comment]
Yep, that fixed the issue for me.

Thanks.
