### ISSUE TITLE
Gevent 1.5 compatability

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#293]
**Describe the bug**
```Traceback (most recent call last):
  File "/Users/nick/.pyenv/versions/autoprovision-3.8/bin/pyinfra", line 5, in <module>
    from pyinfra_cli.__main__ import execute_pyinfra
  File "/Users/nick/.pyenv/versions/3.8.0/envs/autoprovision-3.8/lib/python3.8/site-packages/pyinfra_cli/__main__.py", line 36, in <module>
    gevent.signal(signal.SIGINT, gevent.kill)  # kill any greenlets on ctrl+c
TypeError: 'module' object is not callable```

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/commit/7e6de52fd77ab865164368d90f7c2cfc8369b4fe
