### ISSUE TITLE
Unicode decode errors when trying to copy filenames with unicode in it

### ISSUE THREAD

**Issue by Bystroushaak** [Fizzadar/pyinfra#312]
**Describe the bug**
Unicode decode errors when trying to copy filenames with unicode in it.

```
files.sync("configs/Šablony", "~/Šablony")
```

**To Reproduce**
Create directory called `Šablony` and then try to sync it.

**Expected behavior**
I get Unicode errors all the time. You should probably use encoding from the LANG env var:

```
LANG=cs_CZ.UTF-8
```

as this will happen on all systems with non-ascii encodings.

It seems to me that you are just ignoring string encoding everywhere, as this is not the first place where I've encountered the unicode error.

Also don't take this in the wrong way, but in python2, unicode is generally nightmare. Any reason to stay on py2?

**Meta**
+ Include output of `pyinfra --support`.

```
$ pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19.1-tessa
Traceback (most recent call last):
  File "/home/bystrousak/.local/bin/pyinfra", line 5, in <module>
    from pyinfra_cli.__main__ import execute_pyinfra
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/__main__.py", line 49, in <module>
    execute_pyinfra()
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/__main__.py", line 45, in execute_pyinfra
    cli()
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/main.py", line 86, in _print_support
    print_support_info()
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/prints.py", line 155, in print_support_info
    click.echo('      Release: {0}'.format(platform.uname().release))
AttributeError: 'tuple' object has no attribute 'release'
```

+ How was pyinfra installed (source/pip)?

pip --user

+ Include pyinfra-debug.log (if one was created)

```
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/main.py", line 222, in main
    _main(*args, **kwargs)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/main.py", line 543, in _main
    load_deploy_file(state, filename)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/util.py", line 186, in load_deploy_file
    exec_file(filename)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra_cli/util.py", line 53, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "configure_local_pc.py", line 23, in <module>
    files.sync("configs/Šablony", "~/Šablony")
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra/api/operation.py", line 327, in decorated_func
    for a in args
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra/api/util.py", line 313, in get_arg_value
    return get_template(arg, is_string=True).render(data)
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra/api/util.py", line 227, in get_template
    cache_key = sha1_hash(filename_or_string) if is_string else filename_or_string
  File "/home/bystrousak/.local/lib/python2.7/site-packages/pyinfra/api/util.py", line 260, in sha1_hash
    hasher.update(string.encode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 8: ordinal not in range(128)
```

+ Consider including output with `-vv` and `--debug`.

**Comment by Fizzadar** [comment]
Looks like a couple of Python2 unicode issues here; I've fixed these in https://github.com/Fizzadar/pyinfra/commit/c835d30f0fa40306f0f53e2fb2295830ca513b15. Additionally the `--support` output is another Py2 bug, fixed in https://github.com/Fizzadar/pyinfra/commit/73f37566a3d06e6459f65fca99024b8c39ad7e2c!

**Comment by Bystroushaak** [comment]
Wow, thanks. I can confirm that it works with latest `master` commits.
