### ISSUE TITLE
--key flag assumes RSA

### ISSUE THREAD

**Issue by terrorbyte** [Fizzadar/pyinfra#327]
**Describe the bug**
The `--key` flag assumes that the private key is in RSA format when getting passed to Paramiko here: https://github.com/Fizzadar/pyinfra/blob/263ce59103ae432b662e41c0b18e90da78a1f812/pyinfra/api/connectors/ssh.py#L69

This means that any key that gets passed that's not RSA throws an error.

**To Reproduce**
Run `--key` by pointing it to a different key type.

**Expected behavior**
Try not to assume the key types. I am not familiar with Paramiko, but it looks like if pyinfra were to use `from_private_key` http://docs.paramiko.org/en/stable/api/keys.html#paramiko.pkey.PKey.from_private_key_file 

I am slowly working on some fixes and workaround on my end, if I get it done fast enough I'll submit a PR.

**Meta**
```
$ /home/poptart/.local/bin/pyinfra -v --key /home/poptart/.ssh/id_ed25519 REDACTED exec -- id
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/poptart/.local/lib/python3.7/site-packages/pyinfra/api/host.py", line 85, in connect
    self.connection = self.executor.connect(state, self)
  File "/home/poptart/.local/lib/python3.7/site-packages/pyinfra/api/connectors/ssh.py", line 155, in connect
    kwargs = _make_paramiko_kwargs(state, host)
  File "/home/poptart/.local/lib/python3.7/site-packages/pyinfra/api/connectors/ssh.py", line 138, in _make_paramiko_kwarg
s
    key_password=host.data.ssh_key_password,
  File "/home/poptart/.local/lib/python3.7/site-packages/pyinfra/api/connectors/ssh.py", line 68, in _get_private_key
    filename=filename,
  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 279, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 289, in _read_private_key
    raise SSHException("not a valid " + tag + " private key file")
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2020-06-19T16:08:23Z <Greenlet at 0x17175d8c8710: <bound method Host.connect of REDACTED>(<pyinfra.api.state.Sta
te object at 0x171716ee3f10>)> failed with SSHException

--> An unexpected exception occurred:

  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 289, in _read_private_key
    raise SSHException("not a valid " + tag + " private key file")
paramiko.ssh_exception.SSHException: not a valid RSA private key file

--> The full traceback has been written to pyinfra-debug.log
```

**Comment by Fizzadar** [comment]
Nice spot @terrorbyte, am looking into this! It seems Paramiko's base class method won't actually do anything, instead will need to try each type of key and handle exceptions (parmiko does this here: https://github.com/paramiko/paramiko/blob/master/paramiko/client.py#L674).

**Comment by Fizzadar** [comment]
This should now be fixed/supported in https://github.com/Fizzadar/pyinfra/commit/0770560d954db43b20d9ad83d7f6ca1760bf2f66, which will land in `0.15` later today.
