### ISSUE TITLE
Paramiko requirement needs to be tighter

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#337]
**Describe the bug**
https://github.com/Fizzadar/pyinfra/commit/0770560d954db43b20d9ad83d7f6ca1760bf2f66 introduced support for more key types - but some of these (ed25519) were added in paramiko>2, so need to bump the minimum requirement *or* tolerate the import failure.

``````Traceback (most recent call last):
  File "/usr/local/bin/pyinfra", line 6, in <module>
    from pyinfra_cli.__main__ import execute_pyinfra
  File "/usr/local/lib/python2.7/site-packages/pyinfra_cli/__main__.py", line 8, in <module>
    import pyinfra
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/__init__.py", line 21, in <module>
    from . import facts  # noqa
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/facts/__init__.py", line 11, in <module>
    from . import * # noqa
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/facts/postgresql.py", line 1, in <module>
    from pyinfra.api import FactBase
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/api/__init__.py", line 2, in <module>
    from .deploy import deploy  # noqa: F401 # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/api/deploy.py", line 15, in <module>
    from .host import Host
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/api/host.py", line 7, in <module>
    from .connectors import EXECUTION_CONNECTORS
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/api/connectors/__init__.py", line 1, in <module>
    from . import ansible, chroot, docker, local, mech, ssh, vagrant, winrm
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyinfra/api/connectors/ssh.py", line 12, in <module>
    from paramiko import (
ImportError: cannot import name Ed25519Key``````

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/commit/619fa8628202795cc8058f78e94385a6768da4c4
