### ISSUE TITLE
Cannot debug code in PyCharm

### ISSUE THREAD

**Issue by mjmare** [Fizzadar/pyinfra#450]
I was trying to debug some deploy code in PyCharm and put a breakpoint in the code. I got this error message which is not very informative to me: 

```
Connected to pydev debugger (build 202.7660.27)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 152, in __exit__
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 107, in release
RuntimeError: cannot release un-acquired lock
python-BaseException
```

The code was basically the example on https://docs.pyinfra.com/en/1.x/modules/python.html (see also #449).

**Comment by Fizzadar** [comment]
I'm not sure how to handle this as I don't know where the locking is coming from. It _might_ be that you need to explicitly enable gevent => https://blog.jetbrains.com/pycharm/2012/08/gevent-debug-support/?

**Comment by mjmare** [comment]
Wow, you nailed it! 
Set: Settings | Python Debugger | Gevent compatible debugging to ON.
Learned something today.

**Comment by Fizzadar** [comment]
Excellent! I'm going to add a note about this on the compatability doc (and link to that  doc  from help  & support).

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/commit/1401e704158601e2ffa206cb5f11726747a64a8e

**Comment by rtoton** [comment]
how setup debugging, i can't find info about this
