### ISSUE TITLE
Does not work with encrypted SSH keys on macos 12.2

### ISSUE THREAD

**Issue by anbsky** [Fizzadar/pyinfra#747]
## Describe the bug

Pyinfra is unable to connect when authenticating with an SSH key. Supplying or ommitting ssh_key_password in the inventory or as a cli argument does not change the behavior in any way.

```
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [myhost.com] Authentication error (username=my_user) (Private key file is encrypted)
--> pyinfra error: No hosts remaining!
```

## To Reproduce

`inventory.py`:

```
my_hosts = [
    ('myhost.com', {'ssh_user': 'my_user', 'ssh_key_password': '<password>'}),
]
```

`deploy.py`:

```
from pyinfra.operations import server

server.shell(
    name='Run an ad-hoc command',  # optional name for the operation
    commands='echo "hello world"',
)
```

`pyinfra inventory.py deploy.py`

## Meta

PIP-installed.

```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Darwin
      Platform: macOS-12.2-arm64-arm-64bit
      Release: 21.3.0
      Machine: arm64
    pyinfra: v1.6.1
    Executable: /opt/homebrew/bin/pyinfra
    Python: 3.9.9 (CPython, Clang 13.0.0 (clang-1300.0.29.3))
```

**Comment by Fizzadar** [comment]
Hi @andybeletsky - could you try with specifying the key directly, ie `ssh_key: '/path/to/key'`. You should get a prompt for the password.

Are you using an SSH agent? I think the issue here is when a key isn't explicitly provided the password flow isn't followed, which should only happen if a key is found on disk (by default pyinfra will look for agent + keys if none provided).

**Comment by Fizzadar** [comment]
Closing pending furhter information, happy to reopen with more info :)

**Comment by benjohnde** [comment]
Well, it is a bit sad that this issue did not get proper input. I am having kind of the same issue, using macOS 15.5.

It doesn't matter if I remove the passphrase from the key, or handing over "ssh_key_password", I still get "Private key file is encrypted". It also made me wonder, as I cannot find this exact error in the source code of pyinfra.

```
john@Bens-MacBook-Air pyinfra % pyinfra inventory.py bootstrap.py --dry --debug
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Checking possible group_data at: /Users/john/git/backend/pyinfra/group_data

--> Connecting to hosts...
    [pyinfra.connectors.ssh] Connecting to: 188.34.202.219 ({'allow_agent': False, 'look_for_keys': False, '_pyinfra_ssh_forward_agent': False, '_pyinfra_ssh_config_file': None, '_pyinfra_ssh_known_hosts_file': None, '_pyinfra_ssh_strict_host_key_checking': 'accept-new', '_pyinfra_ssh_paramiko_connect_kwargs': None, 'timeout': 10, 'pkey': PKey(alg=RSA, bits=4096, fp=SHA256:dYZmsE4fm8slJiBkWAozx1rkUEbLjz1IdUhUNZ0dnDQ)})
    [pyinfra.connectors.sshuserclient.client] Loading SSH config: None
    [188.34.202.219] Authentication error (key=/Users/john/.ssh/id_rsa.pyinfra) (Private key file is encrypted)
    [pyinfra.api.state] Failing hosts: 188.34.202.219

--> Disconnecting from hosts...
--> pyinfra error: No hosts remaining!
```

Interestingly, if I am removing my default key without doing anything else:

```
john@Bens-MacBook-Air pyinfra % pyinfra inventory.py bootstrap.py --dry --debug
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Checking possible group_data at: /Users/john/git/backend/pyinfra/group_data

--> Connecting to hosts...
    [pyinfra.connectors.ssh] Connecting to: 188.34.202.219 ({'allow_agent': False, 'look_for_keys': False, '_pyinfra_ssh_forward_agent': False, '_pyinfra_ssh_config_file': None, '_pyinfra_ssh_known_hosts_file': None, '_pyinfra_ssh_strict_host_key_checking': 'accept-new', '_pyinfra_ssh_paramiko_connect_kwargs': None, 'timeout': 10, 'pkey': PKey(alg=RSA, bits=4096, fp=SHA256:dYZmsE4fm8slJiBkWAozx1rkUEbLjz1IdUhUNZ0dnDQ)})
    [pyinfra.connectors.sshuserclient.client] Loading SSH config: None
    [188.34.202.219] Could not connect ([Errno 2] No such file or directory: '/Users/john/.ssh/id_rsa')
    [pyinfra.api.state] Failing hosts: 188.34.202.219

--> Disconnecting from hosts...
--> pyinfra error: No hosts remaining!
john@Bens-MacBook-Air pyinfra %
```

But I my new "pyinfra" key is removed:

```
john@Bens-MacBook-Air pyinfra % pyinfra inventory.py bootstrap.py --dry --debug
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Checking possible group_data at: /Users/john/git/backend/pyinfra/group_data

--> Connecting to hosts...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 900, in gevent._gevent_cgreenlet.Greenlet.run
  File "/opt/homebrew/lib/python3.13/site-packages/pyinfra/api/host.py", line 380, in connect
    self.connector.connect()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/lib/python3.13/site-packages/pyinfra/connectors/ssh.py", line 201, in connect
    return self._connect()
           ~~~~~~~~~~~~~^^
  File "/opt/homebrew/lib/python3.13/site-packages/pyinfra/connectors/ssh.py", line 224, in _connect
    kwargs = self.make_paramiko_kwargs()
  File "/opt/homebrew/lib/python3.13/site-packages/pyinfra/connectors/ssh.py", line 180, in make_paramiko_kwargs
    kwargs["pkey"] = get_private_key(
                     ~~~~~~~~~~~~~~~^
        self.state,
        ^^^^^^^^^^^
        key_filename=ssh_key,
        ^^^^^^^^^^^^^^^^^^^^^
        key_password=self.data["ssh_key_password"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/lib/python3.13/site-packages/pyinfra/connectors/ssh_util.py", line 101, in get_private_key
    raise PyinfraError("No such private key file: {0}".format(key_filename))
pyinfra.api.exceptions.PyinfraError: No such private key file: /Users/john/.ssh/id_rsa.pyinfra
2025-06-30T12:40:59Z <Greenlet at 0x105705940: <bound method Host.connect of Host(188.34.202.219)>> failed with PyinfraError

--> Disconnecting from hosts...
--> pyinfra error in src/gevent/greenlet.py line 900: No such private key file: /Users/john/.ssh/id_rsa.pyinfra
john@Bens-MacBook-Air pyinfra %
``` 

So somehow, some"thing" is overriding the actual key to be used / config.
