### ISSUE TITLE
Crash if the user doesn't have an ssh config file

### ISSUE THREAD

**Issue by sharpobject** [Fizzadar/pyinfra#760]
## Describe the bug
If you try to use the ssh connector but don't have an ssh config file, it crashes.

## To Reproduce
Don't have an ssh config file. Install pyinfra using pip. run a command like `pyinfra localhost exec -- echo "hello world"`

## Expected behavior
It should ssh to localhost instead of crashing.

## Meta
```
foo@bar:~$ pyinfra localhost exec -- echo "hello world"
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/host.py", line 159, in connect
    self.connection = self.executor.connect(self.state, self)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connectors/ssh.py", line 208, in connect
    client.connect(hostname, **kwargs)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connectors/sshuserclient/client.py", line 98, in connect
    hostname, config, forward_agent, missing_host_key_policy, host_keys_file = \
ValueError: not enough values to unpack (expected 5, got 3)
2022-02-19T17:35:27Z <Greenlet at 0x7f027fb25040: <bound method Host.connect of Host(localhost)>> failed with ValueError

--> An unexpected internal exception occurred:

  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connectors/sshuserclient/client.py", line 98, in connect
    hostname, config, forward_agent, missing_host_key_policy, host_keys_file = \
ValueError: not enough values to unpack (expected 5, got 3)

--> The full traceback has been written to pyinfra-debug.log
--> If this is unexpected please consider submitting a bug report on GitHub, for more information run `pyinfra --support`.
foo@bar:~$ cat pyinfra-debug.log
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra_cli/main.py", line 236, in cli
    _main(*args, **kwargs)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra_cli/main.py", line 548, in _main
    connect_all(state)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connect.py", line 35, in connect_all
    greenlet.get()
  File "src/gevent/greenlet.py", line 803, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 371, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "/home/foo/.local/lib/python3.9/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/host.py", line 159, in connect
    self.connection = self.executor.connect(self.state, self)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connectors/ssh.py", line 208, in connect
    client.connect(hostname, **kwargs)
  File "/home/foo/.local/lib/python3.9/site-packages/pyinfra/api/connectors/sshuserclient/client.py", line 98, in connect
    hostname, config, forward_agent, missing_host_key_policy, host_keys_file = \
ValueError: not enough values to unpack (expected 5, got 3)
foo@bar:~$ pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.11.0-49-generic-x86_64-with-glibc2.33
      Release: 5.11.0-49-generic
      Machine: x86_64
    pyinfra: v1.6.2
    Executable: /home/foo/.local/bin/pyinfra
    Python: 3.9.5 (CPython, GCC 10.3.0)
foo@bar:~$
```

**Comment by Fizzadar** [comment]
@sharpobject thank you for reporting this! I've pushed a fix & test for it in https://github.com/Fizzadar/pyinfra/commit/76a9a56d87f4368cd80eebd4f87b2ca9e503c648; will release `v1.6.3` as soon as the tests pass!
