### ISSUE TITLE
multiple files that work individually fail together

### ISSUE THREAD

**Issue by drewp** [Fizzadar/pyinfra#787]
Here's my launcher, using `invoke`:
```python
@task
def all(ctx):
    configs = [
        'users.py',
        'ssh.py',
        'system.py',
        'packages.py',
        'net.py',
        'dns.py',
        'wireguard.py',
        'kube.py',
        'sync.py',
        'mail.py',
    ]
    if together:
        ctx.run(' '.join([cmd, 'inventory.py'] + configs), pty=True)
    else:
        for c in configs:
            ctx.run(' '.join([cmd, 'inventory.py', c]), pty=True, warn=True)
```

The configs work separately.

When I run in `together` mode (pyinfra inventory.py a.py b.py ...), it doesn't work in 2.0rc1:
```
...
    Loading: system.py
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 232, in load_file
    exec_file(filename)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 65, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "system.py", line 41, in <module>
    files.line(path="/etc/fstab", line=line, replace=line)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/operation.py", line 237, in decorated_func
    raise OperationValueError('Cannot have different values for `{0}`.'.format(key))
pyinfra.api.exceptions.OperationValueError: Cannot have different values for `parallel`.
2022-04-07T04:42:36Z <Greenlet at 0x7f649f939e10: load_file(Host(garage))> failed with OperationValueError
```

nor in 1.7.2:
```
--> Preparing operations...
...
    Loading: system.py
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 232, in load_file
    exec_file(filename)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 65, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "system.py", line 41, in <module>
    files.line(path="/etc/fstab", line=line, replace=line)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/operation.py", line 237, in decorated_func
    raise OperationValueError('Cannot have different values for `{0}`.'.format(key))
pyinfra.api.exceptions.OperationValueError: Cannot have different values for `parallel`.
2022-04-07T05:09:46Z <Greenlet at 0x7fd015a68150: load_file(Host(garage))> failed with OperationValueError

--> pyinfra error: Cannot have different values for `parallel`.
    [bang] Command socket/SSH error: SSHException('SSH session not active',)
Traceback (most recent call last):
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 65, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "system.py", line 53, in <module>
    files.put(src='files/docker_daemon.json', dest='/etc/docker/daemon.json')
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/operation.py", line 286, in decorated_func
    commands = [  # convert any strings -> StringCommand's
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/operation.py", line 286, in <listcomp>
    commands = [  # convert any strings -> StringCommand's
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/operations/files.py", line 816, in put
    remote_sum = host.get_fact(Sha1File, path=dest)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/host.py", line 212, in get_fact
    return get_host_fact(self.state, self, name_or_cls, args=args, kwargs=kwargs)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/facts.py", line 279, in get_host_fact
    return get_fact(state, host, name, args=args, kwargs=kwargs, fact_hash=fact_hash)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/facts.py", line 142, in get_fact
    return _get_fact(
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra/api/facts.py", line 228, in _get_fact
    stdout, stderr = split_combined_output(combined_output_lines)
UnboundLocalError: local variable 'combined_output_lines' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 232, in load_file
    exec_file(filename)
  File "/stor6/my/proj/infra/env/lib/python3.9/site-packages/pyinfra_cli/util.py", line 69, in exec_file
    raise UnexpectedExternalError(e, filename)
pyinfra_cli.exceptions.UnexpectedExternalError: <unprintable UnexpectedExternalError object>
2022-04-07T05:09:46Z <Greenlet at 0x7fd015ad7e10: load_file(Host(bang))> failed with UnexpectedExternalError

```

**Comment by Fizzadar** [comment]
Finally tracked this down - way back to v1.3!:

https://github.com/Fizzadar/pyinfra/commit/24b8704c6cdf85d33b82cfa5ad61272625f10945#diff-a0bc476655b0a490b3fd21803c145ea405618bea9902c1a4d74a77380ceaa461L217-L218

Todo: fix, add test

**Comment by Fizzadar** [comment]
Finally tracked this down - way back to v1.3!:

https://github.com/Fizzadar/pyinfra/commit/24b8704c6cdf85d33b82cfa5ad61272625f10945#diff-a0bc476655b0a490b3fd21803c145ea405618bea9902c1a4d74a77380ceaa461L217-L218

Todo: fix, add test

**Comment by Fizzadar** [comment]
Now fixed in v2 (https://github.com/Fizzadar/pyinfra/commit/ca348dd19e6f599712312412f209213eedbc1b8f) + v1.7.3 (https://github.com/Fizzadar/pyinfra/commit/f017edd08833bb8889cb124960f93ad7b2fdb24c)

**Comment by drewp** [comment]
Just confirmed this mode does work for me now, and it's fast!

**Comment by Fizzadar** [comment]
🙏 awesome - thank you for the update!
