### ISSUE TITLE
ImportError: cannot import name 'init' from 'pyinfra.operations'

### ISSUE THREAD

**Issue by jave** [Fizzadar/pyinfra#843]
## Describe the bug
While trying to run an old pyinfra script, I get
ImportError: cannot import name 'init' from 'pyinfra.operations'

23:12:56-joakim@tanaka:~/infra/vagrant_mail_vm$ 	pyinfra  inventory-dev.py  bugvm.py
--> Loading config...
--> Loading inventory...
    Getting Vagrant config...

--> Connecting to hosts...
    [@vagrant/mailvm-dev] Connected

--> Preparing operations...
    Loading: bugvm.py
Traceback (most recent call last):
  File "/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra_cli/util.py", line 68, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "bugvm.py", line 2, in <module>
    from pyinfra.operations import dnf, server, init, files, postgresql
ImportError: cannot import name 'init' from 'pyinfra.operations' (/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra/operations/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra_cli/util.py", line 232, in load_file
    exec_file(filename)
  File "/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra_cli/util.py", line 72, in exec_file
    raise UnexpectedExternalError(e, filename)
pyinfra_cli.exceptions.UnexpectedExternalError: <unprintable UnexpectedExternalError object>
2022-06-24T21:14:06Z <Greenlet at 0x7fb472a44940: load_file(Host(@vagrant/mailvm-dev))> failed with UnexpectedExternalError

--> An unexpected exception occurred in: bugvm.py:

  File "/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra_cli/util.py", line 68, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "bugvm.py", line 2, in <module>
    from pyinfra.operations import dnf, server, init, files, postgresql
ImportError: cannot import name 'init' from 'pyinfra.operations' (/home/joakim/.local/pipx/venvs/pyinfra/lib64/python3.10/site-packages/pyinfra/operations/__init__.py)

## To Reproduce
inventory-dev.py

mail_dev = [
    ('@vagrant/mailvm-dev', {'production':False,
                             'fqdn':'mboxdev.verona.se'})
]

bugvm.py
import sys
from pyinfra.operations import dnf, server, init, files, postgresql
from pyinfra import host

## Expected behavior
to be able to run code like

        init.systemd(
            name='Restart and enable the {} service'.format(service),
            service='{}.service'.format(service),
            running=True,
            restarted=True,
            enabled=True,
        )

## Meta
+ Include output of `pyinfra --support`.
23:11:39-joakim@tanaka:~/infra/vagrant_mail_vm$ pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.18.5-200.fc36.x86_64-x86_64-with-glibc2.35
      Release: 5.18.5-200.fc36.x86_64
      Machine: x86_64
    pyinfra: v2.2
    Executable: /home/joakim/.local/bin/pyinfra
    Python: 3.10.4 (CPython, GCC 12.0.1 20220308 (Red Hat 12.0.1-0))
+ How was pyinfra installed (source/pip)?
pipx
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.

**Comment by jave** [comment]
looking through gitlog, seems I should use systemd.service instead of init.systemd?

However the examples still mention init.systemd

**Comment by jave** [comment]
ok, its not a bug, it might be a doc issue, but i close for now
